/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness: the process is up. No dependencies checked.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness: database, storage and the retention sweeper are all healthy.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Evaluations
         * @description Measured evaluation results and release-gate outcomes for every model (PLAN section 7.3).
         */
        get: operations["evaluations_v1_evaluations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel Job
         * @description Best-effort cancel. A running model call finishes, but its output is discarded.
         */
        delete: operations["cancel_job_v1_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Capabilities
         * @description Enabled features, model cards (incl. mock status) and target age group availability.
         */
        get: operations["capabilities_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/results/{job_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Result Image
         * @description Short-lived signed URL, so the URL itself is the credential and <img> tags work.
         */
        get: operations["get_result_image_v1_results__job_id__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_v1_sessions__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description Immediately delete the upload, all generated images, and all results.
         */
        delete: operations["delete_session_v1_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session Image
         * @description The sanitized upload (metadata removed, orientation applied), via a signed link.
         */
        get: operations["get_session_image_v1_sessions__session_id__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Job */
        post: operations["create_job_v1_sessions__session_id__jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgeEstimationRequest */
        AgeEstimationRequest: {
            /**
             * Task
             * @constant
             */
            task: "age_estimation";
        };
        /** AgeEstimationResult */
        AgeEstimationResult: {
            /**
             * Disclaimer Code
             * @default age_estimate_v1
             * @constant
             */
            disclaimer_code: "age_estimate_v1";
            /** Estimate Years */
            estimate_years: number;
            /**
             * Interval Coverage
             * @description Nominal coverage of range_years, e.g. 0.8.
             */
            interval_coverage: number;
            /** Range Years */
            range_years: [
                number,
                number
            ];
        };
        /** AgeTransformationParams */
        AgeTransformationParams: {
            target_age_group: components["schemas"]["TargetAgeGroup"];
        };
        /** AgeTransformationRequest */
        AgeTransformationRequest: {
            params: components["schemas"]["AgeTransformationParams"];
            /**
             * Task
             * @constant
             */
            task: "age_transformation";
        };
        /** AgeTransformationResult */
        AgeTransformationResult: {
            /**
             * Disclaimer Code
             * @default synthetic_image_v1
             * @constant
             */
            disclaimer_code: "synthetic_image_v1";
            /** Image Url */
            image_url: string;
            /**
             * Image Url Expires At
             * Format: date-time
             */
            image_url_expires_at: string;
            /**
             * Synthetic
             * @default true
             * @constant
             */
            synthetic: true;
            target_age_group: components["schemas"]["TargetAgeGroup"];
            /**
             * Watermarked
             * @default true
             * @constant
             */
            watermarked: true;
        };
        /** Body_create_session_v1_sessions_post */
        Body_create_session_v1_sessions_post: {
            /**
             * Consent
             * @description JSON-encoded Consent object.
             */
            consent?: string | null;
            /**
             * Image
             * @description JPEG, PNG or WebP. Metadata is removed.
             */
            image: string;
        };
        /** CapabilitiesView */
        CapabilitiesView: {
            /** Accepted Formats */
            accepted_formats: string[];
            /**
             * Api Version
             * @default v1
             * @constant
             */
            api_version: "v1";
            /**
             * Consent Version
             * @default 2026-09-v1
             */
            consent_version: string;
            face_detection: components["schemas"]["FaceDetectionView"];
            /** Features */
            features: components["schemas"]["FeatureView"][];
            /** Max Image Side */
            max_image_side: number;
            /** Max Upload Bytes */
            max_upload_bytes: number;
            /** Min Image Side */
            min_image_side: number;
            /** Presentation Uncertain Threshold */
            presentation_uncertain_threshold: number;
            /** Session Ttl Seconds */
            session_ttl_seconds: number;
            /** Target Age Groups */
            target_age_groups: components["schemas"]["TargetGroupView"][];
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: components["schemas"]["ErrorCode"] | ("not_found" | "method_not_allowed" | "http_error");
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
            /** Request Id */
            request_id?: string | null;
            /** Retryable */
            retryable: boolean;
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "invalid_file_type" | "file_too_large" | "image_too_small" | "image_too_large" | "corrupt_image" | "consent_required" | "no_face_detected" | "multiple_faces_detected" | "face_too_small" | "unsupported_target_age_group" | "feature_disabled" | "rate_limited" | "session_not_found" | "job_not_found" | "result_not_found" | "job_not_cancellable" | "adults_only" | "model_error" | "inference_timeout" | "validation_error" | "internal_error";
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** EvaluationMetric */
        EvaluationMetric: {
            /** Families */
            families: components["schemas"]["MetricFamily"][];
            /**
             * Format
             * @enum {string}
             */
            format: "number" | "percent" | "pp" | "ratio" | "years";
            /** Gate Threshold */
            gate_threshold: number | null;
            /** Higher Is Better */
            higher_is_better: boolean;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Overall */
            overall: number;
        };
        /**
         * EvaluationSummary
         * @description A model's evaluation outcome without per-group metrics.
         */
        EvaluationSummary: {
            /** Criteria */
            criteria: components["schemas"]["GateCriterion"][];
            /** Dataset */
            dataset: string | null;
            /** Evaluated At */
            evaluated_at: string | null;
            /** Model Id */
            model_id: string;
            /** Model Name */
            model_name: string;
            /** N */
            n: number | null;
            /** Report */
            report: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "passed" | "failed" | "not_evaluated";
            /**
             * Task
             * @enum {string}
             */
            task: "face_detection" | "age_estimation" | "presentation_estimation" | "age_transformation";
        };
        /** EvaluationView */
        EvaluationView: {
            /** Criteria */
            criteria: components["schemas"]["GateCriterion"][];
            /** Dataset */
            dataset: string | null;
            /** Evaluated At */
            evaluated_at: string | null;
            /** Metrics */
            metrics: components["schemas"]["EvaluationMetric"][];
            /** Model Id */
            model_id: string;
            /** Model Name */
            model_name: string;
            /** N */
            n: number | null;
            /** Report */
            report: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "passed" | "failed" | "not_evaluated";
            /**
             * Task
             * @enum {string}
             */
            task: "face_detection" | "age_estimation" | "presentation_estimation" | "age_transformation";
        };
        /** EvaluationsView */
        EvaluationsView: {
            /** Evaluations */
            evaluations: components["schemas"]["EvaluationView"][];
            /** Source */
            source: string;
        };
        /** FaceCheck */
        FaceCheck: {
            status: components["schemas"]["FaceCheckStatus"];
        };
        /**
         * FaceCheckStatus
         * @enum {string}
         */
        FaceCheckStatus: "not_checked" | "single_face";
        /** FaceDetectionView */
        FaceDetectionView: {
            /** Enabled */
            enabled: boolean;
            /** License */
            license: string | null;
            /** Min Face Side */
            min_face_side: number;
            /** Model Id */
            model_id: string | null;
            /**
             * Policy
             * @default Exactly one face per image; images with no face or several faces are refused.
             */
            policy: string;
            /** Source Url */
            source_url: string | null;
            /** Version */
            version: string | null;
        };
        /** FeatureView */
        FeatureView: {
            /** @description The evaluated real model for this tool, so the UI can explain a mock. */
            candidate?: components["schemas"]["EvaluationSummary"] | null;
            /** Enabled */
            enabled: boolean;
            model: components["schemas"]["ModelCard"] | null;
            task: components["schemas"]["Task"];
        };
        /**
         * GateCriterion
         * @description One pre-registered release gate (docs/PLAN.md section 7.3).
         */
        GateCriterion: {
            /** By Family */
            by_family: components["schemas"]["GateFamilyResult"][];
            /**
             * Comparator
             * @description 'max': measured must be <= limit; 'min': measured must be >= limit.
             * @enum {string}
             */
            comparator: "max" | "min";
            /**
             * Format
             * @enum {string}
             */
            format: "number" | "percent" | "pp" | "ratio" | "years";
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Limit */
            limit: number;
            /**
             * Measured
             * @description Worst case across families; null if not run.
             */
            measured: number | null;
            /** Passed */
            passed: boolean | null;
            /** Worst Family */
            worst_family: string | null;
            /** Worst Group */
            worst_group: string | null;
        };
        /**
         * GateFamilyResult
         * @description A criterion's worst case within one group family (e.g. annotated race).
         */
        GateFamilyResult: {
            /** Family */
            family: string;
            /** Group */
            group: string;
            /** Measured */
            measured: number;
            /** Passed */
            passed: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthView */
        HealthView: {
            /** Checks */
            checks?: {
                [key: string]: boolean;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /** ImageInfo */
        ImageInfo: {
            /**
             * Format
             * @constant
             */
            format: "jpeg";
            /** Height */
            height: number;
            /**
             * Metadata Stripped
             * @default true
             * @constant
             */
            metadata_stripped: true;
            /**
             * Url
             * @description Short-lived signed link to the sanitized image (the 'before').
             */
            url: string;
            /**
             * Url Expires At
             * Format: date-time
             */
            url_expires_at: string;
            /** Width */
            width: number;
        };
        /** JobError */
        JobError: {
            code: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /** JobView */
        JobView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            error?: components["schemas"]["JobError"] | null;
            /** Finished At */
            finished_at: string | null;
            /** Job Id */
            job_id: string;
            model?: components["schemas"]["ModelRef"] | null;
            /** Params */
            params: {
                [key: string]: string;
            };
            /** Progress */
            progress: number;
            /** Result */
            result?: components["schemas"]["AgeEstimationResult"] | components["schemas"]["PresentationEstimationResult"] | components["schemas"]["AgeTransformationResult"] | null;
            /** Session Id */
            session_id: string;
            /** Stage */
            stage: string | null;
            status: components["schemas"]["JobStatus"];
            task: components["schemas"]["Task"];
        };
        /** MetricFamily */
        MetricFamily: {
            /** Family */
            family: string;
            /** Groups */
            groups: components["schemas"]["MetricGroup"][];
            /** Label */
            label: string;
        };
        /** MetricGroup */
        MetricGroup: {
            /**
             * Ci95
             * @description 95% bootstrap confidence interval [low, high].
             */
            ci95: number[];
            /** Group */
            group: string;
            /** N */
            n: number;
            /** Value */
            value: number;
        };
        /** ModelCard */
        ModelCard: {
            /**
             * Eval Passed
             * @description Passed the pre-registered release gates. Real models that haven't are only served in development with an explicit override, and the UI must say so.
             */
            eval_passed: boolean;
            /** Eval Report */
            eval_report: string | null;
            /** Id */
            id: string;
            /** Intended Use */
            intended_use: string;
            /** Is Mock */
            is_mock: boolean;
            /** License */
            license: string;
            /** Limitations */
            limitations: string[];
            /** Source Url */
            source_url: string | null;
            /** Version */
            version: string;
        };
        /** ModelRef */
        ModelRef: {
            /** Id */
            id: string;
            /** Is Mock */
            is_mock: boolean;
            /** Version */
            version: string;
        };
        /** PresentationEstimationRequest */
        PresentationEstimationRequest: {
            /**
             * Task
             * @constant
             */
            task: "presentation_estimation";
        };
        /** PresentationEstimationResult */
        PresentationEstimationResult: {
            /**
             * Disclaimer Code
             * @default presentation_estimate_v1
             * @constant
             */
            disclaimer_code: "presentation_estimate_v1";
            outcome: components["schemas"]["PresentationOutcome"];
            scores: components["schemas"]["PresentationScores"];
            /** Uncertain Threshold */
            uncertain_threshold: number;
        };
        /**
         * PresentationOutcome
         * @enum {string}
         */
        PresentationOutcome: "feminine_presenting" | "masculine_presenting" | "uncertain";
        /** PresentationScores */
        PresentationScores: {
            /** Feminine Presenting */
            feminine_presenting: number;
            /** Masculine Presenting */
            masculine_presenting: number;
        };
        /** SessionCreated */
        SessionCreated: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            face_check: components["schemas"]["FaceCheck"];
            image: components["schemas"]["ImageInfo"];
            /** Session Id */
            session_id: string;
            /**
             * Session Token
             * @description Secret for this session. Returned once; send it as X-Session-Token.
             */
            session_token: string;
        };
        /** SessionView */
        SessionView: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            image: components["schemas"]["ImageInfo"];
            /** Job Ids */
            job_ids: string[];
            /** Session Id */
            session_id: string;
        };
        /**
         * TargetAgeGroup
         * @description Creative targets for the illustrative aging tool. Not predictions.
         * @enum {string}
         */
        TargetAgeGroup: "child" | "teen" | "young_adult" | "middle_aged_adult" | "older_adult";
        /** TargetGroupView */
        TargetGroupView: {
            /** Available */
            available: boolean;
            group: components["schemas"]["TargetAgeGroup"];
            /** Reason */
            reason: string | null;
        };
        /**
         * Task
         * @enum {string}
         */
        Task: "age_estimation" | "presentation_estimation" | "age_transformation";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthView"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthView"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthView"];
                };
            };
        };
    };
    evaluations_v1_evaluations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationsView"];
                };
            };
        };
    };
    get_job_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Session-Token"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancel_job_v1_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Session-Token"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    capabilities_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesView"];
                };
            };
        };
    };
    get_result_image_v1_results__job_id__image_get: {
        parameters: {
            query: {
                exp: number;
                sig: string;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_session_v1_sessions_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCreated"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_session_v1_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Session-Token"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_session_v1_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Session-Token"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_session_image_v1_sessions__session_id__image_get: {
        parameters: {
            query: {
                exp: number;
                sig: string;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_v1_sessions__session_id__jobs_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Session-Token"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgeEstimationRequest"] | components["schemas"]["PresentationEstimationRequest"] | components["schemas"]["AgeTransformationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
