"""Evaluation results shipped with the service (generated by eval/dashboard.py).

The registry enforces the gates through ``ml/calibration/*.json``; this file only
reports them, so the UI can show measured results and why a tool runs on a mock.
"""

from __future__ import annotations

from functools import cache
from pathlib import Path

from facelens_api.schemas.api import EvaluationSummary, EvaluationsView, EvaluationView

EVALUATIONS_FILE = Path(__file__).with_name("evaluations.json")


@cache
def load_evaluations() -> EvaluationsView:
    return EvaluationsView.model_validate_json(EVALUATIONS_FILE.read_text(encoding="utf-8"))


def evaluation_for(task: str) -> EvaluationView | None:
    return next((e for e in load_evaluations().evaluations if e.task == task), None)


def summary_for(task: str) -> EvaluationSummary | None:
    e = evaluation_for(task)
    return EvaluationSummary.model_validate(e.model_dump(exclude={"metrics"})) if e else None
