"""Visible + embedded marking of every generated image as synthetic.

Applied by the job pipeline, not by providers, so no model can skip it. Three layers:
a visible band, a JPEG comment, and XMP carrying the IPTC digital source type
``trainedAlgorithmicMedia`` (the vocabulary C2PA-aware platforms use to label AI-generated
media). Cryptographically signed C2PA manifests need an operator signing certificate;
see docs/RUNBOOK.md.
"""

from __future__ import annotations

import io

from PIL import Image, ImageDraw, ImageFont

LABEL = "SYNTHETIC IMAGE - ILLUSTRATIVE ONLY, NOT A PREDICTION"
JPEG_COMMENT = b"FaceLens synthetic image: illustrative only, not a prediction of appearance."
IPTC_SYNTHETIC = "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia"
XMP_PACKET = (
    '<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>'
    '<x:xmpmeta xmlns:x="adobe:ns:meta/"><rdf:RDF '
    'xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">'
    '<rdf:Description rdf:about="" '
    'xmlns:Iptc4xmpExt="http://iptc.org/std/Iptc4xmpExt/2008-02-29/" '
    'xmlns:dc="http://purl.org/dc/elements/1.1/">'
    f"<Iptc4xmpExt:DigitalSourceType>{IPTC_SYNTHETIC}</Iptc4xmpExt:DigitalSourceType>"
    '<dc:description><rdf:Alt><rdf:li xml:lang="x-default">'
    "Synthetic image generated by FaceLens: illustrative only, not a prediction of appearance."
    "</rdf:li></rdf:Alt></dc:description>"
    '</rdf:Description></rdf:RDF></x:xmpmeta><?xpacket end="w"?>'
).encode()


def watermark_synthetic(image: Image.Image) -> Image.Image:
    out = image.convert("RGB")
    draw = ImageDraw.Draw(out)
    size = max(10, out.width // 40)
    font = ImageFont.load_default(size=size)
    pad = max(4, size // 2)
    text_w = draw.textlength(LABEL, font=font)
    band_h = size + 2 * pad
    top = out.height - band_h
    draw.rectangle((0, top, out.width, out.height), fill=(0, 0, 0))
    draw.text(((out.width - text_w) / 2, top + pad), LABEL, font=font, fill=(255, 255, 255))
    return out


def encode_synthetic_jpeg(image: Image.Image) -> bytes:
    buf = io.BytesIO()
    watermark_synthetic(image).save(
        buf, format="JPEG", quality=90, comment=JPEG_COMMENT, xmp=XMP_PACKET
    )
    return buf.getvalue()
